import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./_components/Navbar";
import { UserProvider } from "./context/UserContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
     <UserProvider>
    <html lang="en" suppressHydrationWarning>
      <head>

        
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
     <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange>
      {children}
     </ThemeProvider>
      </body>
    </html>
    </UserProvider> 
    </ClerkProvider>
  );
}
